name: "Building docker image"
on:
    push:
        branches:
            - master

jobs:
    building_docker_image:
        runs-on: ubuntu-latest
        steps:
            - name: "Installing updates"
              run: sudo apt-get update

            - name: "Inatlling git and docker"
              run: |
                sudo apt-get install git docker.io containerd -y
                sudo systemctl start docker
                sudo systemctl enable --now docker
            
            
            - name: "Cloning the git repository"
              run: |
                sudo git clone -b master https://github.com/soumyabiswas37/github-actions3.git
                ls -l github-actions3/

            - name: "Building Docker image"
              run: sudo docker build -t mycontainer:v1 github-actions3/
            
            - name: "Checking the images"
              run: sudo docker images

            - name: "Running container"
              run: sudo docker run -d --name mycont1 -p 3000:3000 mycontainer:v1
            
            - name: "Checking Container status"
              run: sudo docker ps -a

            - name: "Checking the status"
              run: curl http://localhost:3000